language: node_js
node_js:
  - "6.10.3"
  - "7"
  - "8"
before_install:
  # npm 5.6.0 (the default for 8) has a bug where not all deps are installed (causing tests to fail)
  - npm install -g npm@5.10
notifications:
  email: false
deploy:
  provider: npm
  email: engineering@zapier.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    node: "6.10.3"
  skip_cleanup: true
